### ISSUE TITLE
Multiple keys scan at once ?

### ISSUE THREAD

**Issue by localhero44** [lpaseen/ht16k33#13]
Hi,
Thank you for this nice helpful library.
I've discovered the HT16K33 chip two weeks ago, what a nice chip.
Driving leds and key scan is ok.
Now I would like to know if it's possible to detect 3 keys pressed at the same time.
Regards
David

**Comment by lpaseen** [comment]
The keys are stored in a bitmap so if you press down more than one you get all of them. The problem has to do with the hardware, if you don't have keys with a built in diode (rare) then when you press down 3 keys a 4th can show up. It's because the 3 keys you pressed down creates an electric path for the 4th key. With diodes in place that path can be prevented.
It's more about it in the datasheet for ht16k33.

**Comment by localhero44** [comment]
Thank you for the answer. Yes I was already using the **HT.readKeyRaw(keyData);** function to get the bitmaps.
But wasn't aware of the diodes needed.
