### ISSUE TITLE
Suggestion: public access to _displayram array

### ISSUE THREAD

**Issue by rolfn** [lpaseen/ht16k33#3]
I would like to use your ht16k33 library for [Adafruit's 4-digit-displays](https://www.adafruit.com/products/1269) (Adafruit's library is too complex for my needs). With the functions `setLed/setLedNow` it's not so easy to set associated segments for a complete number at a digit position. It would be nice to have an access to the _displayram array. Then I could set the bytes for the number segments directly (see also http://w8bh.net/avr/AvrSSD1.pdf). What do you think? Thanks in advance.

**Comment by lpaseen** [comment]
I just started to use it my self (that's why I wrote it) and I have 4 alphanumeric letters that I control using setLed/clearLed (see myEnigma). I was thinking that the individual bits needs to be managed somewhere so it might as well be in the library - to put some abstraction between the functions and the physical chip. Say that you have a your 7 seg alphanumeric display or ypur 7 seg, then it won't be even bytes that you manipulate making it a little harder to keep track of things.
On the other hand I guess it doesn't hurt to add it, it could be handled similar to the key array, add readDisplayRaw/setDisplayRaw or make _displayram public.

**Comment by rolfn** [comment]
Thank you for the quick response. The benefit of setting a whole byte: I could use a "translation table", e.g. the index 6 gives me  0x7D (all the needed segments for the number 6 as 7-segment). What's about the following (or similar)?

``` cpp
void HT16K33::setDisplayRaw(uint8_t idx, uint8_t val) {
  if (idx < sizeof(_displayram) {
    _displayram[idx] = val;
  }  
}
```

Greetings from Berlin.

Edit: I see: The displayram array is now public. Good for my needs. Thank you.

**Comment by lpaseen** [comment]
I moved displayram to public since the only thing you can hurt is your self so now you can direct update displayRam and then just call sendLed to get it pushed out.

As for translation table - still only works if you align it at even bytes or have a bigger one to gove all digits. I mean - if you pack it tight then one segment on the first digit may be byte 0 bit 0 but on the second digit the same segment could be byte0 bit 7. 

FYI - I started this about a month ago but I'm new at coding and still working on the practical use of it so I'm glad for any suggestions to improvements. I plan on add things to it - more examples for a start - and test everything more. Now when I know someone else using it I will keep that in mind when changing things around (which I do since this is more of alpha/beta state).

**Comment by rolfn** [comment]
I want to use your library with two commercial displays from the company Adafruit. Here are the addresses properly aligned. First tests are successful. Again: many thanks.
